// /* eslint-disable import/no-extraneous-dependencies */
// import 'whatwg-fetch'
// import 'custom-event-polyfill'
import 'core-js/es/promise'
import 'core-js/es/array'
import 'core-js/es/object'
import 'core-js/es/symbol'
// import 'core-js/es6/string'
// import 'core-js/es6/map'
// import 'core-js/es6/set'
// import 'core-js/web/dom-collections'
// import 'core-js/modules/web.dom.iterable'
